const products = [
  {
    id: 1,
    name: "Yamaha FZ 25",
    price: 128000,
    category: "cc",
    image: "images/FZ-25.jpg",
    rating: 4,
    reviews: 28,
  },
  {
    id: 2,
    name: "Yamaha FZ C",
    price: 135000,
    category: "fuel",
    image: "images/FZ-C.jpg",
    rating: 5,
    reviews: 32,
  },
  {
    id: 3,
    name: "Yamaha FZ R1",
    price: 2050000,
    category: "cc",
    image: "images/FZ-R1.jpg",
    rating: 4,
    reviews: 22,
  },
  {
    id: 4,
    name: "Yamaha FZ MS",
    price: 175000,
    category: "brand",
    image: "images/FZ-MS.png",
    rating: 3,
    reviews: 14,
  },
  {
    id: 5,
    name: "Yamaha R15 V3R",
    price: 168000,
    category: "cc",
    image: "images/FZ-V3R.png",
    rating: 5,
    reviews: 25,
  },
  {
    id: 6,
    name: "Yamaha MT15",
    price: 250000,
    category: "mileage",
    image: "images/FZ-MT15.png",
    rating: 5,
    reviews: 21,
  },
  {
    id: 7,
    name: "Yamaha R1 CR",
    price: 2200000,
    category: "cc",
    image: "images/FZ-R1CR.png",
    rating: 5,
    reviews: 23,
  },
  {
    id: 8,
    name: "Yamaha R1M",
    price: 3200000,
    category: "cc",
    image: "images/FZ-R1M.png",
    rating: 5,
    reviews: 30,
  },
  {
    id: 9,
    name: "Yamaha R1M CR",
    price: 3600000,
    category: "cc",
    image: "images/FZ-R1MCR.png",
    rating: 5,
    reviews: 28,
  },
  {
    id: 10,
    name: "Yamaha R3",
    price: 270000,
    category: "cc",
    image: "images/FZ-R3.png",
    rating: 5,
    reviews: 20,
  },
  {
    id: 11,
    name: "Yamaha R6",
    price: 870000,
    category: "brand",
    image: "images/FZ-R6.png",
    rating: 5,
    reviews: 18,
  },
  {
    id: 12,
    name: "Yamaha FZ S",
    price: 168000,
    category: "mileage",
    image: "images/FZ-S.png",
    rating: 4,
    reviews: 22,
  },
  {
    id: 13,
    name: "Yamaha FZ S1",
    price: 178000,
    category: "mileage",
    image: "images/FZ-S1.png",
    rating: 4,
    reviews: 19,
  },
  {
    id: 14,
    name: "Yamaha R15 V2",
    price: 148000,
    category: "mileage",
    image: "images/FZ-V2.png",
    rating: 4,
    reviews: 17,
  },
  {
    id: 15,
    name: "Yamaha R15 V2R",
    price: 158000,
    category: "mileage",
    image: "images/FZ-V2R.png",
    rating: 4,
    reviews: 21,
  },
  {
    id: 16,
    name: "Yamaha R15 V3B",
    price: 168000,
    category: "mileage",
    image: "images/FZ-V3B.png",
    rating: 5,
    reviews: 23,
  },
  {
    id: 17,
    name: "Yamaha R15 V3CR",
    price: 170000,
    category: "mileage",
    image: "images/FZ-V3CR.jpg",
    rating: 4,
    reviews: 24,
  },
  {
    id: 18,
    name: "Yamaha R15 V3CR W",
    price: 172000,
    category: "mileage",
    image: "images/FZ-V3CRW.png",
    rating: 5,
    reviews: 26,
  },
  {
    id: 19,
    name: "Yamaha R15 V3CR W",
    price: 172000,
    category: "mileage",
    image: "images/FZ-V3CRW.png",
    rating: 5,
    reviews: 26,
  },
  {
    id: 20,
    name: "Yamaha R15 V4Y",
    price: 175000,
    category: "mileage",
    image: "images/FZ-V3Y.png",
    rating: 5,
    reviews: 27,
  },
];
